create_clock -period 10.000 -name CLK -waveform {0.000 5.000} [get_ports CLK]
create_generated_clock -name clk50mhz -source [get_ports CLK] -divide_by 2 [get_pins clk50mhz_reg/Q]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]
set_property PACKAGE_PIN E3 [get_ports CLK]
set_property PACKAGE_PIN D9 [get_ports RESET]
set_property PACKAGE_PIN A9 [get_ports UART_RX]
set_property PACKAGE_PIN D10 [get_ports UART_TX]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
