# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraints selected for write.
Resolution: This message can indicate that there are no constraints for the design, or it can indicate that the used_in flags are set such that the constraints are ignored. This later case is used when running synth_design to not write synthesis constraints to the resulting checkpoint. Instead, project constraints are read when the synthesized design is opened.}}  -suppress 
set_msg_config  -id {filemgmt 56-3}  -string {{WARNING: [filemgmt 56-3] Board Part Repository Path: Could not find the directory '/root/.Xilinx/Vivado/2019.1/xhub/board_store'.}}  -suppress 
set_msg_config  -id {Board 49-44}  -string {{WARNING: [Board 49-44] Exception: boost::filesystem::status: Permission denied: "/root/.Xilinx/Vivado/2019.1/xhub/board_store"}}  -suppress 
set_msg_config  -id {IP_Flow 19-4067}  -string {{WARNING: [IP_Flow 19-4067] Ignoring invalid widget type specified checkbox.Providing a default widget}}  -suppress 
set_msg_config  -id {filemgmt 56-12}  -string {{WARNING: [filemgmt 56-12] File '/home/rafa/ufrgs/steel-core/soc/bench/tb_gpio.v' cannot be added to the project because it already exists in the project, skipping this file}}  -suppress 
set_msg_config  -id {USF-XSim-62}  -string {{ERROR: [USF-XSim-62] 'elaborate' step failed with error(s). Please check the Tcl console output or '/home/rafa/ufrgs/steel-core/vivado/steel-core.sim/sim_1/behav/xsim/elaborate.log' file for more information.}}  -suppress 
set_msg_config  -id {Vivado 12-4473}  -string {{ERROR: [Vivado 12-4473] Detected error while running simulation. Please correct the issue and retry this operation.}}  -suppress 
set_msg_config  -id {filemgmt 56-3}  -string {{WARNING: [filemgmt 56-3] IPUserFilesDir: Could not find the directory '/home/rafa/ufrgs/steel-core/vivado/steel-core.ip_user_files'.}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rafa/ufrgs/steel-core/vivado/steel-core.cache/wt [current_project]
set_property parent.project_path /home/rafa/ufrgs/steel-core/vivado/steel-core.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/rafa/ufrgs/steel-core/vivado/steel-core.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/rafa/ufrgs/steel-core/rtl/globals.vh
read_mem /home/rafa/ufrgs/basic-tests/gpio.mem
read_verilog -library xil_defaultlib {
  /home/rafa/ufrgs/steel-core/rtl/alu.v
  /home/rafa/ufrgs/steel-core/rtl/branch_unit.v
  /home/rafa/ufrgs/steel-core/soc/bus_arbiter.v
  /home/rafa/ufrgs/steel-core/rtl/csr_file.v
  /home/rafa/ufrgs/steel-core/rtl/decoder.v
  /home/rafa/ufrgs/steel-core/soc/gpio.v
  /home/rafa/ufrgs/steel-core/rtl/imm_generator.v
  /home/rafa/ufrgs/steel-core/rtl/integer_file.v
  /home/rafa/ufrgs/steel-core/rtl/load_unit.v
  /home/rafa/ufrgs/steel-core/rtl/machine_control.v
  /home/rafa/ufrgs/steel-core/soc/ram.v
  /home/rafa/ufrgs/steel-core/rtl/steel_top.v
  /home/rafa/ufrgs/steel-core/rtl/store_unit.v
  /home/rafa/ufrgs/steel-core/soc/soc_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/rafa/ufrgs/steel-core/vivado/steel-core.srcs/constrs_1/new/contraints.xdc
set_property used_in_implementation false [get_files /home/rafa/ufrgs/steel-core/vivado/steel-core.srcs/constrs_1/new/contraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_top_utilization_synth.rpt -pb soc_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
