webtalk_init -webtalk_dir /home/rafa/ufrgs/steel-core/vivado/steel-core.sim/sim_1/behav/xsim/xsim.dir/tb_load_unit_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May  3 17:21:21 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6ed276ad-7c1b-4553-b4bd-7259fd5716b5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b8561a63f69e41d98a2e12d383a11daf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 19.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1041.328 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.10_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "119196_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1232447671 -regid "" -xml /home/rafa/ufrgs/steel-core/vivado/steel-core.sim/sim_1/behav/xsim/xsim.dir/tb_load_unit_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/rafa/ufrgs/steel-core/vivado/steel-core.sim/sim_1/behav/xsim/xsim.dir/tb_load_unit_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/rafa/ufrgs/steel-core/vivado/steel-core.sim/sim_1/behav/xsim/xsim.dir/tb_load_unit_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
